[versions]
kotlin = "2.1.0"
#kotlin = "2.3.0"
kotlinx-datetime = "0.6.1"
kotlinx-serialization-json = "1.7.2"
kotlinx-coroutines = "1.8.1"
javafx = "23"
javafx-plugin = "0.0.14"
gluonfx-plugin = "1.0.28"
controlsfx = "11.1.2"
ikonli = "12.4.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-javafx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx", version.ref = "kotlinx-coroutines" }
controlsfx = { module = "org.controlsfx:controlsfx", version.ref = "controlsfx" }
ikonli-materialdesign = { module = "org.kordamp.ikonli:ikonli-materialdesign-pack", version.ref = "ikonli" }
ikonli-javafx = { module = "org.kordamp.ikonli:ikonli-javafx", version.ref = "ikonli" }

# Libraries can be bundled together for easier import
[bundles]
kotlinx-ecosystem = ["kotlinx-datetime", "kotlinx-serialization-json", "kotlinx-coroutines-core"]
ikonli = ["ikonli-materialdesign", "ikonli-javafx"]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
javafx-gradle = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
gluonfx-gradle = { id = "com.gluonhq.gluonfx-gradle-plugin", version.ref = "gluonfx-plugin" }